server {
    listen 443 ssl;
    server_name test.lab.local;
    
    ssl_certificate /etc/ssl/certs/test.lab.local.pem;
    ssl_certificate_key /etc/ssl/private/test.lab.local.key;
    
    root /var/www/html;
    index index.html;
    
    location / {
        try_files $uri $uri/ =404;
    }
}

server {
    listen 80;
    server_name test.lab.local;
    return 301 https://$server_name$request_uri;
}
